language: node_js
node_js:
  - "7.8.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - curl --ftp-create-dirs --upload-file "{dist/*}" -u $FTP_USER:$FTP_PASSWORD ftp://itbt.in
